// <auto-generated />
using System;
using Beadando.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beadando.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    [Migration("20241121143010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Beadando.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Basketball"
                        });
                });

            modelBuilder.Entity("Beadando.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Los Angeles Lakers"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chicago Bulls"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Miami Heat"
                        });
                });

            modelBuilder.Entity("Beadando.Models.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoriteLeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteLeagueId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HalfTimeScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            FinalScore = "2:1",
                            HalfTimeScore = "1:1",
                            HomeTeamId = 1,
                            LeagueId = 1,
                            Report = "Manchester United secured a victory in the final minutes!",
                            StartTime = new DateTime(2023, 11, 1, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 4,
                            FinalScore = "3:2",
                            HalfTimeScore = "2:1",
                            HomeTeamId = 3,
                            LeagueId = 1,
                            Report = "Liverpool edged out Barcelona in a thrilling game.",
                            StartTime = new DateTime(2023, 11, 3, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 6,
                            FinalScore = "112:108",
                            HalfTimeScore = "55:50",
                            HomeTeamId = 5,
                            LeagueId = 2,
                            Report = "LeBron James led the Lakers to a narrow victory over the Warriors.",
                            StartTime = new DateTime(2023, 11, 5, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AwayTeamId = 8,
                            FinalScore = "98:95",
                            HalfTimeScore = "45:50",
                            HomeTeamId = 7,
                            LeagueId = 2,
                            Report = "The Bulls triumphed in a tightly contested match.",
                            StartTime = new DateTime(2023, 11, 6, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Beadando.Models.UserPreference", b =>
                {
                    b.HasOne("Beadando.Models.League", "FavoriteLeague")
                        .WithMany()
                        .HasForeignKey("FavoriteLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavoriteLeague");
                });

            modelBuilder.Entity("Match", b =>
                {
                    b.HasOne("Beadando.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Beadando.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Beadando.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Beadando.Models.League", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Beadando.Models.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
